### ISSUE TITLE
Allow promise functions to throw Errors, and have them turned into rejected Promises?

### ISSUE THREAD

**Issue by ghost** [fponticelli/thx.promise#2]
For promise callbacks that do synchronous operations, it would be convenient to be able to throw a `thx.Error` and have it turned into a rejected promise (if this function is running within a promise chain).

It might also be nice to have an equivalent of the `Promise.try` from libraries like bluebird or Q, so you can start a promise chain with synchronous code that might throw an error, and have the error turned into a rejected Promise.  http://bluebirdjs.com/docs/api/promise.try.html

**Comment by fponticelli** [comment]
Do you think it is not confusing to have try/catch around `mapSuccess` but not around `mapSuccessPromise`?

**Comment by ghost** [comment]
I feel like the promise library could remove the need for a lot of try/catch cruft if the synchronous code executing inside promise functions was allowed to throw errors, rather than having to wrap things in try/catch yourself.

``` haxe
// Following the naming convention of mapSuccess and mapSuccessPromise, we could
// have Promise.tries and Promise.triesPromise:

return Promise.tries(function({
  // synchronous code that might throw, and returns a value (which is promisified - like mapSuccess)
})
.mapSuccess...


return Promise.triesPromise(function() {
  // Synchronous code that might throw, and returns a promise
})
.mapSuccessPromise(function(v) {
  // Currently, to handle synchronous errors, you have to:
  return try {
    // Code that might throw...
    Promise.value(123);
  } catch (e : Error) {
    Promise.error(e);
  }

  // It would be nice to just be able to do this:
  // Code that might throw
  // return new promise
})
.mapSuccess(function(v) {
  // Currently, to handle synchronous errors, you have to:
  return try {
    // code that might throw...
    return 123;
  } catch (e : Error) {
    // what do I do with an error here?  Re-throw it?
  }

  // Would be nice to just:
  // code that might throw...
  // return new value
});
```

**Comment by fponticelli** [comment]
That is a compelling reason and it has been brought.
